FROM circumcaetera_img

ADD ./files/ /

RUN apt-get install -y  screen autoconf automake build-essential liblmdb-dev pkgconf zlib1g-dev \
    && chmod 700 /build_nginx.sh && \
    /build_nginx.sh

EXPOSE 22 
    
CMD ["/usr/sbin/sshd", "-D"]
